// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mtclimRun
List mtclimRun(List forcing_dataR, List settings);
RcppExport SEXP mtclimR_mtclimRun(SEXP forcing_dataRSEXP, SEXP settingsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forcing_dataR(forcing_dataRSEXP);
    Rcpp::traits::input_parameter< List >::type settings(settingsSEXP);
    rcpp_result_gen = Rcpp::wrap(mtclimRun(forcing_dataR, settings));
    return rcpp_result_gen;
END_RCPP
}
