// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mtclimRun
int mtclimRun(int x, List forcing_dataR);
RcppExport SEXP mtclimR_mtclimRun(SEXP xSEXP, SEXP forcing_dataRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type forcing_dataR(forcing_dataRSEXP);
    rcpp_result_gen = Rcpp::wrap(mtclimRun(x, forcing_dataR));
    return rcpp_result_gen;
END_RCPP
}
