// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mtclimRun
List mtclimRun(List forcing_dataR, List settings);
RcppExport SEXP _mtclimR_mtclimRun(SEXP forcing_dataRSEXP, SEXP settingsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forcing_dataR(forcing_dataRSEXP);
    Rcpp::traits::input_parameter< List >::type settings(settingsSEXP);
    rcpp_result_gen = Rcpp::wrap(mtclimRun(forcing_dataR, settings));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mtclimR_mtclimRun", (DL_FUNC) &_mtclimR_mtclimRun, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_mtclimR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
