# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mtclimRun <- function(nrecs, forcing_dataR, settings) {
    .Call('mtclimR_mtclimRun', PACKAGE = 'mtclimR', nrecs, forcing_dataR, settings)
}

